# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-12 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ws_interlace.models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0002_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ws_interlace.Answer')),
                ('image', models.ImageField(upload_to=ws_interlace.models.get_image_path)),
            ],
        ),
    ]
