# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0004_auto_20170312_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=models.SlugField(default=' ', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 3, 13, 15, 7, 1, 287439, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksheet',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 3, 13, 15, 7, 12, 337354, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
