# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0005_auto_20170313_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
