# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0006_upload_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='worksheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ws_interlace.Worksheet'),
        ),
    ]
