# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0007_auto_20170313_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='num',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='answer',
            name='worksheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ws_interlace.Worksheet'),
        ),
    ]
