# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0008_auto_20170314_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='worksheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ws_interlace.Worksheet'),
        ),
    ]
