# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0009_auto_20170316_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='slug',
        ),
    ]
