# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0013_auto_20170317_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='student',
            new_name='section_id',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='description',
        ),
        migrations.AlterField(
            model_name='answer',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
