# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0014_auto_20170317_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='section_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='answer',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
