# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0015_auto_20170317_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='answer',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
