# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0016_auto_20170317_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='img_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
