# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0017_answer_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='student_id',
        ),
    ]
