# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0020_auto_20170407_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image_file',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='answer',
            name='image_url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
