# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0022_auto_20170407_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='image_url',
        ),
    ]
