# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0023_auto_20170407_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image_file',
            field=models.ImageField(default='/Users/johnspiva/Google Drive/Programming/capstone/media/answer_images/ws-1', upload_to='images'),
        ),
        migrations.AddField(
            model_name='answer',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
