# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0025_auto_20170407_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='img_url',
        ),
    ]
