# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0026_remove_answer_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='section_id',
            new_name='section_type',
        ),
    ]
