# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0027_auto_20170410_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worksheet',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='worksheet',
            new_name='section',
        ),
    ]
