# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0028_auto_20170410_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='section_type',
        ),
    ]
