# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0030_section_section_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='section_name',
        ),
    ]
