# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0031_remove_answer_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
