# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0033_auto_20170411_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
