# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0034_worksheet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ws_interlace.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='worksheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ws_interlace.Worksheet'),
        ),
    ]
