# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0035_auto_20170413_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
