# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0037_classroom_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ManyToManyField(null=True, related_name='students', to='ws_interlace.Classroom'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='ws_interlace.Classroom'),
        ),
    ]
