# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0039_auto_20170421_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='ws_interlace.Student'),
        ),
    ]
