# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0041_auto_20170421_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ws_interlace.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ManyToManyField(blank=True, related_name='students', to='ws_interlace.Classroom'),
        ),
    ]
