# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0045_auto_20170503_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='classroom',
        ),
        migrations.AddField(
            model_name='answer',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
