# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 23:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0046_auto_20170503_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='collaborators',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000), default=list, size=None),
        ),
    ]
