# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_interlace', '0047_answer_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='collaborators',
        ),
    ]
